function [ p ] = crewcdf_rsfsv_bin( fileName, varargin )
%CREWCDF_RSFSV Loads Rohde & Schwarz trace into crew cdf
%
%   It is possible to load files generated by Rohde & Schwarz
%   .py
%
%   See also CREWCDF_STRUCT, CREWCDF_WISPY, CREWCDF_IMEC, CREWCDF_TELOS

%   Mikolaj Chwalisz for CREW, COUWBAT

iP = inputParser;
iP.addRequired('fileName', @ischar);
iP.addParamValue('Name','');
iP.addParamValue('Location',[0, 0, 0]);
iP.parse(fileName, varargin{:});
options = iP.Results;
if isempty(options.Name)
    [ path, options.Name] = fileparts(fileName);
    % options.Name = strrep(options.Name, '-', '');
end

p = struct( ...
    'Name'       , options.Name, ...
    'Location'   , options.Location, ...
    'CenterFreq' , [] , ...
    'BW'         , 0, ...
    'Tstart'     , '01-Jan-1970 00:00:00', ...
    'SampleTime' , [], ...
    'Power'      , [], ...
    'Meta'       , struct());

delimiter = ';';


fileId = fopen([fileName '.txt']);
fline = fgets(fileId);

while ischar(fline)
    fline = deblank(fline);
    if isempty(fline)
        fline = fgets(fileId);
        continue
    end
    item = strsplit(fline, delimiter);
    name = genvarname(regexprep(char(item(1)),'[^\w]','_'));
    val = str2num(char(item(2)));
    if isempty(val)
        p.Meta.(name) = char(item(2));
    else
        p.Meta.(name) = val;
        if length(item) == 3
            p.Meta.([name '_Unit']) = char(item(3));
        end
    end
    if strcmpi(name, 'values')
        % All Meta data has been read, from the next line it is only data
        break
    end
    fline = fgets(fileId);
end

format = '%f %f ';
c = textscan(fileId, format, 'delimiter', delimiter , ...
    'ReturnOnError', 0);

p.CenterFreq = c{1};
p.PowerSample = c{2}';

fclose(fileId);

% Get real data
fileId = fopen(fileName);

c = fread(fileId, [p.Meta.Values + 2, Inf], 'float32');

p.Power = c(3:end,:)';

fseek(fileId,0,'bof');
SampleTime = fread(fileId,inf,'double',4*p.Meta.Values);
p.Tstart = datestr(SampleTime(1)/86400+datenum('1/1/1970'));
tStart_epoch = (datenum(p.Tstart)-datenum(1970,1,1)) * 86400;
p.SampleTime = SampleTime - tStart_epoch;



fclose(fileId);
end

